### ISSUE TITLE
Always getting the value of the previous query...?

### ISSUE THREAD

**Issue by darconeous** [Galvant/gpibusb-firmware#1]
Hello there!

I recently [acquired an Agilent/HP 8753A vector network analyzer](https://plus.google.com/112605652687169110943/posts/PvsF6A9PLYS) for a great price and I started looking for a good way to utilize that GPIB port on the back to get the data out of it. I found your adapter on eBay for just $60. As an added bonus, it was completely open-source. Great deal.

I hooked it up and it _kinda_ works, but I'm getting very strange behavior. Take, for example, the following exchange:

> SEND: `+A:16`
> SEND: `+TEST`
> RECV: `testing` <small>_GOOD_</small>
> SEND: `*IDN?`
> RECV: `Read error occurred.` <small>_???_</small>
> SEND: `*IDN?`
> RECV: `HEWLETT PACKARD,8753A,0,1.01` <small>_GOOD_</small>
> SEND: `*STAR?` <small>_Start Frequency: Should return 300kHz_</small>
> RECV: `HEWLETT PACKARD,8753A,0,1.01` <small>_What the...?_</small>
> SEND: `*STAR?`
> RECV: `3.000000000000000E+05` <small>_GOOD_</small>
> SEND: `*STOP?` <small>_Stop Frequency: Should return 3GHz_</small>
> RECV: `3.000000000000000E+05` <small>_BAD. This was just the start frequency again!_</small>
> SEND: `*STOP?`
> RECV: `3.000000000000000E+09` <small>_GOOD_</small>

As you can see, it seems like for every query I do, I end up getting the result from the previous command. Any idea why this might be happening? I'll continue investigating, but I just wanted to ping you to see if you recognized this behavior.

**Comment by scasagrande** [comment]
Sounds like data is getting stuck in the output buffer. Something is happening at the start, which is causing everything to get pushed back. What are you using to communicate with your virtual serial port (vsp)? Try using some basic terminal software first (eg Terminite on Windows) which will automatically retrieve all available data from the vsp.

Please copy a complete dump, including full error messages.
