### ISSUE TITLE
manual response from the adapter

### ISSUE THREAD

**Issue by felis** [Galvant/gpibusb-firmware#7]
Hello,

I just received Galvant GPIB to USB adapter and trying to talk to it via the terminal. I'm using minicom on ubuntu. I open minicom and type '++ver'. I'm getting no response from the adapter. In USB trace, I can see my characters sent out to the FTDI chip but nothing comes back. Please advice.

Regards,
Oleg.

**Comment by scasagrande** [comment]
Hi Oleg,
Minicom does not work with the firmware v5 (which was shipped on your adapter) as it sends each character as they are typed. For the v5 firmware, use software which sends all character at once when you hit enter (for example, CuteCom on Linux).

This issue has been resolved in the v6 beta which you can download and install from this respository.

**Comment by felis** [comment]
Thanks! I figured this out - coding the USB Host support for Arduino atm (to work with my shield ), and the converter is already talking :-).
