### ISSUE TITLE
unsigned bytes (>128)

### ISSUE THREAD

**Issue by fransschreuder** [Galvant/gpibusb-firmware#8]
Hello,
I am trying to read my oscilloscope (HP54111D). When I set it to binary mode (BYTE) it seems to return only the sequence 0xEF, 0xBF, 0xBD instead of any value >128. I don't know whether this is a "feature" of the scope or of the gpibusb-firmware. When I set it to ascii mode the values are read out correctly.
Do you have any clue?
Thanks

**Comment by fransschreuder** [comment]
@cgranade , @scasagrande I don't know if you are getting messages from this thread if I don't mention you...

**Comment by scasagrande** [comment]
Hey sorry about that. I doubt this has anything to do with my gpibusb firmware. Binary mode works just fine for every other binary transfer I've done. 

I know that with scopes, you have to manipulate the binary data afterwards. You will need to query the scope for adjustment information (y = a + bx , ie offset and scaling).
